services:
  db:
    image: postgres:18
    container_name: nexora_postgres
    environment:
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora_dev_password
      POSTGRES_DB: nexora_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: