"""add opportunities, opportunity_eligibility, opportunity_skills

Revision ID: 9c578d75e66e
Revises: c6372d7cc238
Create Date: 2026-08-26 04:01:19.713526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c578d75e66e'
down_revision: Union[str, Sequence[str], None] = 'c6372d7cc238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('INTERNSHIP', 'HACKATHON', 'COMPETITION', 'SCHOLARSHIP', 'RESEARCH', 'WORKSHOP', 'CONFERENCE', 'CAMPUS_EVENT', 'OTHER', name='opportunitycategory'), nullable=False),
    sa.Column('organizer', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='opportunitymode'), nullable=False),
    sa.Column('registration_url', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='opportunitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('opportunity_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('eligible_branches', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('eligible_semesters', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('is_uncertain', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('opportunity_skills',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_skills')
    op.drop_table('opportunity_eligibility')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS opportunitycategory")
    op.execute("DROP TYPE IF EXISTS opportunitymode")
    op.execute("DROP TYPE IF EXISTS opportunitystatus")
